version: '3.8'

services:
  django:
    build: .
    command: gunicorn proto_app.wsgi:application --bind 127.0.0.1:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod