import os

DEBUG = os.getenv('DJANGO_DEBUG', True)
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')
DB_PATH = os.getenv('DJANGO_DATABASE_PATH')
STATIC_FILE_PATH = os.getenv('DJANGO_STATIC_PATH')
MEDIA_FILE_PATH = os.getenv('DJANGO_MEDIA_PATH')

print('DJANGO_DEBUG', DEBUG)
print('DJANGO_SECRET_KEY', SECRET_KEY)
print('DJANGO_ALLOWED_HOSTS', ALLOWED_HOSTS)
print('DJANGO_DATABASE_PATH', DB_PATH)
print('DJANGO_STATIC_PATH', STATIC_FILE_PATH)
print('DJANGO_MEDIA_PATH', MEDIA_FILE_PATH)
