# Generated by Django 3.0.7 on 2020-06-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=70)),
                ('post_url', models.SlugField(blank=True, max_length=100, null=True)),
                ('post_details', models.TextField()),
                ('post_published_date', models.DateField(blank=True)),
            ],
        ),
    ]
