# Generated by Django 3.1.2 on 2021-08-25 16:59

import ckeditor.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import settings.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=70)),
                ('note_url', models.SlugField(blank=True, max_length=100, null=True)),
                ('note_details', ckeditor.fields.RichTextField()),
                ('note_published_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=70, unique=True)),
                ('project_code', models.CharField(blank=True, max_length=70, null=True, unique=True)),
                ('project_active', models.BooleanField(default=True)),
                ('project_url', models.SlugField(blank=True, max_length=100, null=True)),
                ('project_intro', ckeditor.fields.RichTextField()),
                ('project_start_date', models.DateField(blank=True, default=datetime.date.today)),
                ('project_end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'permissions': (('can_list_posts', 'List Posts'), ('can_view_post', 'View Post Details'), ('can_create_post', 'Create Post'), ('can_invite_users', 'Invite Project Users'), ('can_list_users', 'List Project Users'), ('can_manage_project', 'Manage Project')),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=70)),
                ('post_active', models.BooleanField(default=True)),
                ('post_url', models.SlugField(blank=True, max_length=100, null=True)),
                ('post_details', ckeditor.fields.RichTextField()),
                ('post_published_date', models.DateTimeField(auto_now=True)),
                ('post_image_1', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/%Y/%m/%d/')),
                ('post_attachment', models.FileField(blank=True, max_length=255, null=True, upload_to='files/%Y/%m/%d/', validators=[settings.validators.validate_file_type_size])),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.project')),
            ],
        ),
    ]
