# Generated by Django 3.0.7 on 2020-07-13 07:59

import datetime
from django.db import migrations, models
import settings.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=70)),
                ('post_active', models.BooleanField(default=True)),
                ('post_url', models.SlugField(blank=True, max_length=100, null=True)),
                ('post_details', models.TextField()),
                ('post_published_date', models.DateField(blank=True, default=datetime.date.today)),
                ('post_image_1', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/%Y/%m/%d/')),
                ('post_image_2', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/%Y/%m/%d/')),
                ('post_attachment', models.FileField(blank=True, max_length=255, null=True, upload_to='files/%Y/%m/%d/', validators=[settings.validators.validate_file_type_size])),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=70, unique=True)),
                ('project_active', models.BooleanField(default=True)),
                ('project_url', models.SlugField(blank=True, max_length=100, null=True)),
                ('project_intro', models.TextField()),
                ('project_start_date', models.DateField(blank=True, default=datetime.date.today)),
                ('project_end_date', models.DateField(blank=True, null=True)),
                ('project_logo', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/%Y/%m/%d/')),
            ],
            options={
                'permissions': (('can_list_posts', 'List Posts'), ('can_view_post', 'View Post Details'), ('can_create_post', 'Create Post'), ('can_invite_users', 'Invite Project Users'), ('can_list_users', 'List Project Users'), ('can_manage_project', 'Manage Project')),
            },
        ),
    ]
