# Generated by Django 3.0.7 on 2020-06-25 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_published_date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
