# Generated by Django 3.0.7 on 2020-06-26 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20200625_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_attachment',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%D/'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='files/%Y/%m/%D/'),
        ),
    ]
