# Generated by Django 3.0.7 on 2020-06-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20200626_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image_1',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='files/%Y/%m/%D/'),
        ),
    ]
